[colors.bright]
black = "0x1c61c2"
blue = "0x00ff00"
cyan = "0x0abdc6"
green = "0xd300c4"
magenta = "0x711c91"
red = "0xff0000"
white = "0xd7d7d5"
yellow = "0xf57800"

[colors.dim]
black = "0x1c61c2"
blue = "0x123e7c"
cyan = "0x0abdc6"
green = "0xd300c4"
magenta = "0x711c91"
red = "0xff0000"
white = "0xd7d7d5"
yellow = "0xf57800"

[colors.normal]
black = "0x123e7c"
blue = "0x123e7c"
cyan = "0x0abdc6"
green = "0xd300c4"
magenta = "0x711c91"
red = "0xff0000"
white = "0xd7d7d5"
yellow = "0xf57800"

[colors.primary]
background = "#000512"
foreground = "0x0abdc6"

[font]
size = 11.0

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Semibold"

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "F11"

[window]
decorations = "none"
opacity = 1.0

[window.padding]
x = 0
y = 0
